# docker-compose.yml
services:

  mysql:
    image: mysql:8.0
    container_name: snow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: demo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./snowflake.sql:/docker-entrypoint-initdb.d   # mysql脚本
    networks: 
      - snow-network

  redis:
    image: redis:7.0
    container_name: snow-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks: 
      - snow-network
    command: ["redis-server", "--requirepass", "treeman"]

  app:
    image: snowflake-app:latest
    container_name: snowflake-app
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev   # 可切换不同环境
    ports:
      - "9000:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - snow-network

networks:
  snow-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
