server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: mysql
  redis:
    port: 6379
    host: 192.168.68.68
    password: treeman
    timeout: 10s
    lettuce:
      pool:
          # 连接池中的最小空闲连接
        min-idle: 0
          # 连接池中的最大空闲连接
        max-idle: 8
          # 连接池的最大数据库连接数
        max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#        视图解析器配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/

#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.treeman.snowflake.pojo